#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export FASTLANE_OPT_OUT_USAGE=1
export GOPATH="/Users/fred/Documents/Development/go"
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

export ANDROID_HVPROTO=ddm
export PATH="$PATH:/Users/Shared/Android/sdk/platform-tools/"
