#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source `brew --prefix`/etc/profile.d/z.sh
alias android-studio="open -a /Applications/Android\ Studio.app"

# added by travis gem
[ -f /Users/fred/.travis/travis.sh ] && source /Users/fred/.travis/travis.sh
export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"

export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
